matrix:
  include:
    - name: "nodejs proto files"
      language: node_js
      node_js: "node"
      before_script:
        - cd proto-node
        - yarn install
      script:
        - yarn build
      #deploy:
      #  skip_cleanup: true
      #  provider: npm
      #  email: $NPM_DPL_EMAIL
      #  api_key: $NPM_DPL_TOKEN

    - name: "shared JS"
      language: node_js
      node_js: "node"
      before_script:
        - cd shared-js
        - yarn install
      script:
        - yarn build
      #deploy:
      #  skip_cleanup: true
      #  provider: npm
      #  email: $NPM_DPL_EMAIL
      #  api_key: $NPM_DPL_TOKEN

    - name: "grpc server"
      language: java
      jdk: openjdk11
      install: mvn clean install -DskipTests -pl grpc-server -am -Djdk.tls.client.protocols="TLSv1,TLSv1.1,TLSv1.2"
      script: mvn test -pl grpc-server -am -Djdk.tls.client.protocols="TLSv1,TLSv1.1,TLSv1.2"
