version: '3'
services:
  server_js:
    build:
      context: ./
      dockerfile: server-js/Dockerfile
    links:
      - mongo
      - server_java
    volumes:
      - "./data/leveldb:/opt/server-js/db"
      - "./data/uploads:/opt/server-js/uploads"
    restart: on-failure

  mongo:
    image: mongo:3
    volumes:
      - "./data/mongo:/data/db"
    restart: on-failure

  server_java:
    build: ./
    restart: on-failure
    volumes:
      - "./data/fonts:/root/.fonts"

  frontend:
    build:
      context: ./
      dockerfile: frontend/Dockerfile
      args:
        - COMMIT_ID
    ports:
      - "8081:80"
    restart: on-failure
