version: '3'
services:
  server_js:
    build: ./server-js
    links:
      - mongo
      - server-report
    volumes:
      - "./data/leveldb:/opt/server/db"
      - "./data/uploads:/opt/server/uploads"
    restart: on-failure

  mongo:
    image: mongo:3
    volumes:
      - "./data/mongo:/data/db"
    ports:
      - "27017:27017"
    restart: on-failure

  server_report:
    build: ./
    restart: on-failure
    volumes:
      - "./data/fonts:/root/.fonts"

  frontend:
    build:
      context: ./frontend
      args:
        - COMMIT_ID
    ports:
      - "8081:80"
    restart: on-failure
